if(NOT DEFINED INPUT_FILES)
  message(FATAL_ERROR "INPUT_FILES is required")
endif()

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OUTPUT is required")
endif()

string(REPLACE "|" ";" input_files "${INPUT_FILES}")

set(json_files "")
foreach(input_file IN LISTS input_files)
  string(STRIP "${input_file}" input_file)
  if(input_file STREQUAL "")
    continue()
  endif()

  if(NOT EXISTS "${input_file}")
    message(FATAL_ERROR "Input metatypes file does not exist: ${input_file}")
  endif()
  list(APPEND json_files "${input_file}")
endforeach()
list(SORT json_files)

file(WRITE "${OUTPUT}" "[\n")
set(first_entry TRUE)
foreach(json_file IN LISTS json_files)
  file(READ "${json_file}" content)
  string(STRIP "${content}" content)
  if(content STREQUAL "")
    continue()
  endif()
  string(SUBSTRING "${content}" 0 1 first_char)
  string(LENGTH "${content}" content_length)
  math(EXPR last_char_index "${content_length} - 1")
  string(SUBSTRING "${content}" "${last_char_index}" 1 last_char)
  if(first_char STREQUAL "[" AND last_char STREQUAL "]")
    math(EXPR inner_length "${content_length} - 2")
    string(SUBSTRING "${content}" 1 "${inner_length}" content)
    string(STRIP "${content}" content)
    if(content STREQUAL "")
      continue()
    endif()
  endif()

  if(first_entry)
    set(first_entry FALSE)
  else()
    file(APPEND "${OUTPUT}" ",\n")
  endif()
  file(APPEND "${OUTPUT}" "${content}")
endforeach()
file(APPEND "${OUTPUT}" "\n]\n")
