if(NOT DEFINED INPUT_LIST)
  message(FATAL_ERROR "INPUT_LIST is required")
endif()

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OUTPUT is required")
endif()

file(READ "${INPUT_LIST}" input_paths_text)
string(REPLACE "\n" ";" input_paths "${input_paths_text}")

set(entries "")
foreach(input_path IN LISTS input_paths)
  string(STRIP "${input_path}" input_path)
  if(input_path STREQUAL "")
    continue()
  endif()

  file(READ "${input_path}" content)
  string(STRIP "${content}" content)
  string(LENGTH "${content}" content_length)
  if(content_length LESS 2)
    continue()
  endif()

  math(EXPR inner_length "${content_length} - 2")
  string(SUBSTRING "${content}" 1 "${inner_length}" inner)
  string(STRIP "${inner}" inner)
  if(NOT inner STREQUAL "")
    list(APPEND entries "${inner}")
  endif()
endforeach()

file(WRITE "${OUTPUT}" "[\n")
set(first_entry TRUE)
foreach(entry IN LISTS entries)
  if(first_entry)
    set(first_entry FALSE)
  else()
    file(APPEND "${OUTPUT}" ",\n")
  endif()
  file(APPEND "${OUTPUT}" "${entry}")
endforeach()
file(APPEND "${OUTPUT}" "\n]\n")
