# Generated from tooling/module.json; do not resolve stale global providers.
if(NOT CMAKE_PREFIX_PATH)
  set(CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}/build/deps/prefix")
endif()
find_path(_tooling_HoloNightConfig NAMES HoloNightConfigConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HoloNightConfig lib64/cmake/HoloNightConfig share/HoloNightConfig/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HoloNightConfig)
  message(FATAL_ERROR "Missing HoloNightConfig in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HoloNightConfig_DIR "${_tooling_HoloNightConfig}" CACHE PATH "Explicit local provider" FORCE)
find_path(_tooling_HolonightQt NAMES HolonightQtConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HolonightQt lib64/cmake/HolonightQt share/HolonightQt/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HolonightQt)
  message(FATAL_ERROR "Missing HolonightQt in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HolonightQt_DIR "${_tooling_HolonightQt}" CACHE PATH "Explicit local provider" FORCE)
find_path(_tooling_HoloNightSystemServices NAMES HoloNightSystemServicesConfig.cmake PATHS ${CMAKE_PREFIX_PATH} PATH_SUFFIXES lib/cmake/HoloNightSystemServices lib64/cmake/HoloNightSystemServices share/HoloNightSystemServices/cmake NO_DEFAULT_PATH NO_CACHE)
if(NOT _tooling_HoloNightSystemServices)
  message(FATAL_ERROR "Missing HoloNightSystemServices in explicit CMAKE_PREFIX_PATH. Run task deps or supply a provider prefix.")
endif()
set(HoloNightSystemServices_DIR "${_tooling_HoloNightSystemServices}" CACHE PATH "Explicit local provider" FORCE)
